swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/UserProfile"
        "400":
          description: Invalid Fields
        "418":
          description: User is a teapot🫖
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/accounts:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User's accounts API call
      description: API for fetching user accounts ids and type (check, saving, credit...)
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Users accounts retrieved successfully
          schema:
            $ref: "#/definitions/Accounts"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  # USER TRANSACTIONS
  /user/{accountId}/balance:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Current Balance of {accountId}.
      description: API call for the account balance.
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: string
          in: path
          name: accountId
          description: account ID
          required: true
      responses:
        "200":
          description: Balance retrieved successfully
          schema:
            $ref: "#/definitions/Balance"
        "400":
          description: Bad request.
        "401":
          description: Token not matching.
        "500":
          description: Internal Server Error.
        "503":
          description: Server unavailable (down/maintenance).

  /user/{accountId}/transactions:
    post:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Lasts N transactions of account.
      description: API call for last N transactions of the account.
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: integer
          in: header
          name: ArrayLength
          description: Length of N, if omitted =default is 20
          required: false
        - type: string
          in: path
          name: AccountId
          description: account ID
          required: true
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Bad request.
        "401":
          description: Token not matching.
        "500":
          description: Internal Server Error.
        "503":
          description: Server unavailable (down/maintenance).

  /user/{accountId}/transactions/{startDate,endDate}:
    post:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Transactions of account between dates.
      description: API call for transactions of the account between start and end dates.
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: string
          in: path
          name: AccountId
          description: account ID
          required: true
        - type: integer
          in: path
          name: startDate
          description: start date
          required: true
        - type: integer
          in: path
          name: endDate
          description: end date
          required: true
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Bad request.
        "401":
          description: Token not matching.
        "500":
          description: Internal Server Error.
        "503":
          description: Server unavailable (down/maintenance).

  /user/{accountId}/transaction/{transactionId}:
    post:
      tags:
        - User Transactions
      summary: Fetch a detailed transaction
      description: API call for one detailed transaction {transactionId}
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: string
          in: path
          name: transactionId
          description: User transaction Id
          required: true
      responses:
        "200":
          description: Detailed transaction retrieved successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Bad request.
        "500":
          description: Internal Server Error
    put:
      tags:
        - User Transactions
      summary: Edit a detailed transaction
      description: Edit one item in detailed transaction
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: string
          in: path
          name: transactionId
          description: User transaction Id
          required: true
        - type: number
          in: path
          name: editType
          description: transaction type (type/category/note) to edit
          required: true
        - type: string
          in: path
          name: editContent
          description: transaction content to edit
          required: true

      responses:
        "200":
          description: Detailed transaction retrieved successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Bad request.
        "500":
          description: Internal Server Error
    delete:
      tags:
        - User Transactions
      summary: Fetch a detailed transaction
      description: API for getting one detailed transaction
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: string
          in: path
          name: transactionId
          description: User transaction Id
          required: true
      responses:
        "200":
          description: Detailed transaction retrieved successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Bad request.
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Balance:
    type: object
    properties:
      balance:
        type: number
        format: float
      available:
        type: boolean
  Accounts:
    type: object
    properties:
      acType:
        type: integer
      accountId:
        type: string
  Transactions:
    type: object
    properties:
      transactionId:
        type: integer
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      type:
        type: string
      category:
        type: string
      notes:
        type: string
