swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/UserProfile"
        "400":
          description: Invalid Fields
        "418":
          description: User is a teapot🫖
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/accounts:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User's accounts API call
      description: API for fetching user accounts ids and type (check, saving, credit...)
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Users accounts retrieved successfully
          schema:
            $ref: "#/definitions/Accounts"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  # USER TRANSACTIONS
  /accounts/{accountId}/balance:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts module
      summary: Current Balance of {accountId}.
      description: API call for the account balance. *Balance is integer in ¢ to avoid float*
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: string
          in: path
          name: accountId
          description: account ID
          required: true
      responses:
        "200":
          description: Balance retrieved successfully
          schema:
            $ref: "#/definitions/Balance"
        "400":
          description: Bad request.
        "401":
          description: Token not matching.
        "404":
          description: Account not found in database
        "500":
          description: Internal Server Error.
        "503":
          description: Server unavailable (down/maintenance).

  /account/{accountId}/lastsTransactions:
    post:
      security:
        - Bearer: []
      tags:
        - Accounts module
      summary: Lasts N transactions of account.
      description: API call for last N transactions of the account.
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true

        - in: body
          name: arrayLength
          description: Length of N, *if omitted =default is 20*
          required: false
          schema:
            $ref: "#/definitions/arrayLength"

        - type: string
          in: path
          name: accountId
          description: account Id
          required: true
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Bad request.
        "401":
          description: Token not matching.
        "404":
          description: Account not found in database
        "500":
          description: Internal Server Error.
        "503":
          description: Server unavailable (down/maintenance).

  /account/{accountId}/getTransactions:
    post:
      security:
        - Bearer: []
      tags:
        - Accounts module
      summary: Transactions of account between dates.
      description: API call for transactions of the account between start and end dates.
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: string
          in: path
          name: accountId
          description: account ID
          required: true
        - in: body
          name: dates
          description: start date, end date.
          required: false
          schema:
            $ref: "#/definitions/dates"

      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Bad request.
        "401":
          description: Token not matching.
        "404":
          description: Account not found in database
        "500":
          description: Internal Server Error.
        "503":
          description: Server unavailable (down/maintenance).

  /transaction/{transactionId}:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions module
      summary: Fetch a detailed transaction
      description: API call for one detailed transaction {transactionId}
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: string
          in: path
          name: transactionId
          description: User transaction Id
          required: true
      responses:
        "200":
          description: Detailed transaction retrieved successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Bad request.
        "404":
          description: Transaction not found in database
        "500":
          description: Internal Server Error
  /transaction/{transactionId}/edit:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions module
      summary: Edit a detailed transaction
      description: Edit one item in detailed transaction
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - type: string
          in: path
          name: transactionId
          description: User transaction Id
          required: true
        - in: body
          name: editBody
          description: edit type (0:category, 1:note) and content (*can be "empty" to delete previous content*).
          required: true
          schema:
            $ref: "#/definitions/editBody"

      responses:
        "200":
          description: Detailed transaction edited successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Bad request.
        "404":
          description: Transaction not found in database
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        format: email
        description: user email
      password:
        type: string
        format: password
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        format: email
        description: user email
      password:
        type: string
        format: password
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
            format: email
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Balance:
    type: object
    properties:
      balance:
        type: integer
      available:
        type: boolean
  Accounts:
    type: object
    properties:
      acType:
        type: integer
      accountId:
        type: string
  arrayLength:
    type: object
    properties:
      arrayLength:
        type: integer
        default: 20
  dates:
    type: object
    properties:
      startDate:
        type: string
        format: date
      endDate:
        type: string
        format: date
  editBody:
    type: object
    properties:
      editType:
        type: integer
      editContent:
        type: string
  Transactions:
    type: object
    properties:
      transactionId:
        type: integer
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: integer
      type:
        type: integer
      category:
        type: integer
      notes:
        type: string
